version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g webpack webpack-cli
  pre-build:
    commands:
      - npm install
  build: 
    commands: 
      - npm run build

artifacts:
  files:
    - package.json
    - package-lock.json
    - webpack.config.json
    - 'public/**/*'
    - 'bin/**/*'
    - 'routes/**/*'
    - 'views/**/*'